name: CodeMender Find
description: Scans a repository for vulnerabilities

runs:
  using: composite
  steps:
    - name: Install CodeMender
      uses: codemender-demo/cm-install@v0.1
        
    - name: Run cm find
      shell: bash
      run: |
        echo "Running in dir: $(pwd)"
        cm find .
